[package]
name = "kernel-print"
version = "0.1.0"
description = "Windows kernel printing library."
authors = ["not-matthias <26800596+not-matthias@users.noreply.github.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/not-matthias/kernel-print-rs"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntapi = { version = "0.3.4", default-features = false, features = ["kernel"] }

[features]
default = ["format"]
std_name = []
format = []